/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountBalancesDto } from './accountBalances';


export interface AccountItemDto { 
    id: string;
    /**
     * Ej: CHECKING | SAVINGS
     */
    product_type: string;
    /**
     * ISO-4217
     */
    currency: string;
    status: string;
    balances: AccountBalancesDto;
}

