/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountItemDto } from './accountItem';


export interface AccountsOverviewResponseDto { 
    accounts: Array<AccountItemDto>;
}

