/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountLookupItemDto { 
    account_id: string;
    /**
     * Número de cuenta normalizado (12 dígitos).
     */
    account_number: string;
    /**
     * Nombre mostrado del titular (demo).
     */
    display_name: string;
    product_type: string;
    currency: string;
    status: string;
}

