/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountLookupItemDto } from './accountLookupItem';


export interface AccountLookupResponseDto { 
    account: AccountLookupItemDto;
}

