/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountBalancesDto { 
    /**
     * Decimal string
     */
    ledger: string;
    /**
     * Decimal string
     */
    available: string;
    /**
     * Decimal string
     */
    hold: string;
}

