/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountActivityItemDto } from './accountActivityItem';


export interface AccountActivityResponseDto { 
    items: Array<AccountActivityItemDto>;
    page: number;
    size: number;
    /**
     * Opcional; si no hay fuente upstream para total, puede omitirse o null.
     */
    total?: number | null;
}

