/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatementItemDto } from './statementItem';


export interface AccountStatementResponseDto { 
    items: Array<StatementItemDto>;
    page: number;
    size: number;
    /**
     * Opcional si no hay total disponible.
     */
    total?: number | null;
}

