/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActivateRequestDto { 
    registration_id: string;
    full_name: string;
    tin: string;
    birth_date: string;
    country: string;
    email: string;
    phone: string;
    /**
     * Recomendado si tu UI exige aceptación.
     */
    accepted_terms?: boolean | null;
}

