/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KycObjectStatusDto } from './kycObjectStatus';
import { RegistrationStateDto } from './registrationState';


export interface ConfirmKycResponseDto { 
    registration_id: string;
    state: RegistrationStateDto;
    statuses: Array<KycObjectStatusDto>;
    confirmed_at?: string | null;
}
export namespace ConfirmKycResponseDto {
}


