/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CounterpartyViewDto { 
    account_id: string;
    account_number: string;
    display_name: string;
    account_type: string;
}

