/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreatePaymentResponseDto { 
    payment_id: string;
    status: CreatePaymentResponseDto.StatusEnum;
}
export namespace CreatePaymentResponseDto {
    export const StatusEnum = {
        Pending: 'pending',
        Posted: 'posted',
        Rejected: 'rejected',
        Failed: 'failed'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


