/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreatePaymentRequestDto { 
    source_account: string;
    destination_account: string;
    currency: string;
    /**
     * Decimal string
     */
    amount: string;
    memo?: string | null;
}

