/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FinishWebauthnRegistrationRequestDto { 
    request_id: string;
    /**
     * JSON resultante de navigator.credentials.create()
     */
    credential_json: string;
}

