/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentStepDto } from './paymentStep';


export interface GetPaymentResponseDto { 
    payment_id: string;
    status: string;
    idempotency_key: string;
    source_account: string;
    destination_account: string;
    currency: string;
    amount: string;
    steps: Array<PaymentStepDto>;
    created_at: string;
}

