/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const KycDocTypeDto = {
    IdFront: 'id_front',
    Selfie: 'selfie'
} as const;
export type KycDocTypeDto = typeof KycDocTypeDto[keyof typeof KycDocTypeDto];

