/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KycUploadStatusDto } from './kycUploadStatus';
import { KycDocTypeDto } from './kycDocType';


export interface KycObjectStatusDto { 
    doc_type: KycDocTypeDto;
    status: KycUploadStatusDto;
    bucket: string;
    key: string;
    etag?: string | null;
}
export namespace KycObjectStatusDto {
}


