/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const KycUploadStatusDto = {
    Pending: 'pending',
    Confirmed: 'confirmed',
    Unspecified: 'unspecified'
} as const;
export type KycUploadStatusDto = typeof KycUploadStatusDto[keyof typeof KycUploadStatusDto];

