/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const OccupationTypeDto = {
    Student: 'student',
    Employee: 'employee',
    SelfEmployed: 'self_employed',
    Unemployed: 'unemployed',
    Retired: 'retired'
} as const;
export type OccupationTypeDto = typeof OccupationTypeDto[keyof typeof OccupationTypeDto];

