/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchProfileRequestPreferencesInnerDto { 
    channel: PatchProfileRequestPreferencesInnerDto.ChannelEnum;
    opt_in: boolean;
}
export namespace PatchProfileRequestPreferencesInnerDto {
    export const ChannelEnum = {
        Email: 'email',
        Sms: 'sms',
        Push: 'push'
    } as const;
    export type ChannelEnum = typeof ChannelEnum[keyof typeof ChannelEnum];
}


