/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchAccountLimitsHttpResponseDto { 
    account_id: string;
    daily_out: string;
    daily_in: string;
}

