/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Actualiza límites diarios de entrada/salida. Campos omitidos o null => no se modifican. 
 */
export interface PatchAccountLimitsHttpRequestDto { 
    /**
     * Decimal string (>=0). Ej: \'500.00\'
     */
    daily_out?: string | null;
    /**
     * Decimal string (>=0). Ej: \'1000.00\'
     */
    daily_in?: string | null;
}

