/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PatchProfileRequestPreferencesInnerDto } from './patchProfileRequestPreferencesInner';


export interface PatchProfileRequestDto { 
    full_name?: string | null;
    email?: string | null;
    phone?: string | null;
    preferences?: Array<PatchProfileRequestPreferencesInnerDto> | null;
}

