/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PresignedHeaderDto } from './presignedHeader';
import { KycDocTypeDto } from './kycDocType';


export interface PresignedUploadDto { 
    doc_type: KycDocTypeDto;
    bucket: string;
    key: string;
    upload_url: string;
    headers: Array<PresignedHeaderDto>;
    max_bytes: number;
    content_type: string;
    expires_in_seconds: number;
}
export namespace PresignedUploadDto {
}


