/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RefreshSessionResponseDto { 
    /**
     * TTL de la sesión (segundos). Cookie rotada/extendida.
     */
    session_expires_in: number;
}

