/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const RegistrationStateDto = {
    Started: 'started',
    ContactVerified: 'contact_verified',
    Consented: 'consented',
    Activated: 'activated',
    Rejected: 'rejected',
    Unspecified: 'unspecified'
} as const;
export type RegistrationStateDto = typeof RegistrationStateDto[keyof typeof RegistrationStateDto];

