/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CounterpartyViewDto } from './counterpartyView';


export interface StatementItemDto { 
    /**
     * Journal/entry id del ledger
     */
    journal_id: string;
    booked_at: string;
    currency: string;
    direction: StatementItemDto.DirectionEnum;
    /**
     * Decimal string
     */
    amount: string;
    kind: string;
    /**
     * Referencia externa / external_ref
     */
    memo?: string | null;
    counterparty_account_id?: string | null;
    counterparty?: CounterpartyViewDto;
}
export namespace StatementItemDto {
    export const DirectionEnum = {
        Debit: 'debit',
        Credit: 'credit'
    } as const;
    export type DirectionEnum = typeof DirectionEnum[keyof typeof DirectionEnum];
}


