/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KycDocTypeDto } from './kycDocType';


export interface UploadedObjectDto { 
    doc_type: KycDocTypeDto;
    bucket: string;
    key: string;
    etag?: string | null;
    size_bytes?: number | null;
    content_type?: string | null;
}
export namespace UploadedObjectDto {
}


