/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WhoamiResponseDto { 
    subject_id_oidc: string;
    customer_id?: string | null;
    roles: Array<string>;
    user_status: string;
}

