// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bank/ops/v1/ops.proto

package opsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationChannel int32

const (
	NotificationChannel_NOTIFICATION_CHANNEL_UNSPECIFIED NotificationChannel = 0
	NotificationChannel_NOTIFICATION_CHANNEL_EMAIL       NotificationChannel = 1
	NotificationChannel_NOTIFICATION_CHANNEL_SMS         NotificationChannel = 2
	NotificationChannel_NOTIFICATION_CHANNEL_PUSH        NotificationChannel = 3
)

// Enum value maps for NotificationChannel.
var (
	NotificationChannel_name = map[int32]string{
		0: "NOTIFICATION_CHANNEL_UNSPECIFIED",
		1: "NOTIFICATION_CHANNEL_EMAIL",
		2: "NOTIFICATION_CHANNEL_SMS",
		3: "NOTIFICATION_CHANNEL_PUSH",
	}
	NotificationChannel_value = map[string]int32{
		"NOTIFICATION_CHANNEL_UNSPECIFIED": 0,
		"NOTIFICATION_CHANNEL_EMAIL":       1,
		"NOTIFICATION_CHANNEL_SMS":         2,
		"NOTIFICATION_CHANNEL_PUSH":        3,
	}
)

func (x NotificationChannel) Enum() *NotificationChannel {
	p := new(NotificationChannel)
	*p = x
	return p
}

func (x NotificationChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_bank_ops_v1_ops_proto_enumTypes[0].Descriptor()
}

func (NotificationChannel) Type() protoreflect.EnumType {
	return &file_bank_ops_v1_ops_proto_enumTypes[0]
}

func (x NotificationChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationChannel.Descriptor instead.
func (NotificationChannel) EnumDescriptor() ([]byte, []int) {
	return file_bank_ops_v1_ops_proto_rawDescGZIP(), []int{0}
}

type GetAuditEventsByTraceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OpenAPI: query trace_id (uuid)
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// OpenAPI: query limit (min 1, max 1000, default 200)
	// Si no se envía, el server debe aplicar el default (200).
	Limit *wrapperspb.Int32Value `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// OpenAPI: header X-Subject (maxLength 200), optional.
	// Si no se envía, se usa "internal" (según OpenAPI).
	XSubject      *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=x_subject,json=xSubject,proto3" json:"x_subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditEventsByTraceRequest) Reset() {
	*x = GetAuditEventsByTraceRequest{}
	mi := &file_bank_ops_v1_ops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditEventsByTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditEventsByTraceRequest) ProtoMessage() {}

func (x *GetAuditEventsByTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_ops_v1_ops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditEventsByTraceRequest.ProtoReflect.Descriptor instead.
func (*GetAuditEventsByTraceRequest) Descriptor() ([]byte, []int) {
	return file_bank_ops_v1_ops_proto_rawDescGZIP(), []int{0}
}

func (x *GetAuditEventsByTraceRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GetAuditEventsByTraceRequest) GetLimit() *wrapperspb.Int32Value {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *GetAuditEventsByTraceRequest) GetXSubject() *wrapperspb.StringValue {
	if x != nil {
		return x.XSubject
	}
	return nil
}

type GetAuditEventsByTraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AuditEventItem      `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"` // required in OpenAPI => repeated por defecto "presente"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditEventsByTraceResponse) Reset() {
	*x = GetAuditEventsByTraceResponse{}
	mi := &file_bank_ops_v1_ops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditEventsByTraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditEventsByTraceResponse) ProtoMessage() {}

func (x *GetAuditEventsByTraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_ops_v1_ops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditEventsByTraceResponse.ProtoReflect.Descriptor instead.
func (*GetAuditEventsByTraceResponse) Descriptor() ([]byte, []int) {
	return file_bank_ops_v1_ops_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuditEventsByTraceResponse) GetEvents() []*AuditEventItem {
	if x != nil {
		return x.Events
	}
	return nil
}

type AuditEventItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Acción auditada (ej. payments.create, login, logout).
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// Timestamp del evento (ISO-8601).
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Identificador del recurso asociado.
	ResourceId    string `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEventItem) Reset() {
	*x = AuditEventItem{}
	mi := &file_bank_ops_v1_ops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEventItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEventItem) ProtoMessage() {}

func (x *AuditEventItem) ProtoReflect() protoreflect.Message {
	mi := &file_bank_ops_v1_ops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEventItem.ProtoReflect.Descriptor instead.
func (*AuditEventItem) Descriptor() ([]byte, []int) {
	return file_bank_ops_v1_ops_proto_rawDescGZIP(), []int{2}
}

func (x *AuditEventItem) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEventItem) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *AuditEventItem) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type GetNotificationPrefsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OpenAPI: query customer_id (uuid)
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// OpenAPI: header X-Subject (maxLength 200), optional.
	// Si no se envía, se usa "internal" (según OpenAPI).
	XSubject      *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=x_subject,json=xSubject,proto3" json:"x_subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationPrefsRequest) Reset() {
	*x = GetNotificationPrefsRequest{}
	mi := &file_bank_ops_v1_ops_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationPrefsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationPrefsRequest) ProtoMessage() {}

func (x *GetNotificationPrefsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_ops_v1_ops_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationPrefsRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationPrefsRequest) Descriptor() ([]byte, []int) {
	return file_bank_ops_v1_ops_proto_rawDescGZIP(), []int{3}
}

func (x *GetNotificationPrefsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GetNotificationPrefsRequest) GetXSubject() *wrapperspb.StringValue {
	if x != nil {
		return x.XSubject
	}
	return nil
}

type GetNotificationPrefsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Prefs         []*NotificationPrefItem `protobuf:"bytes,1,rep,name=prefs,proto3" json:"prefs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationPrefsResponse) Reset() {
	*x = GetNotificationPrefsResponse{}
	mi := &file_bank_ops_v1_ops_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationPrefsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationPrefsResponse) ProtoMessage() {}

func (x *GetNotificationPrefsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_ops_v1_ops_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationPrefsResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationPrefsResponse) Descriptor() ([]byte, []int) {
	return file_bank_ops_v1_ops_proto_rawDescGZIP(), []int{4}
}

func (x *GetNotificationPrefsResponse) GetPrefs() []*NotificationPrefItem {
	if x != nil {
		return x.Prefs
	}
	return nil
}

type NotificationPrefItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       NotificationChannel    `protobuf:"varint,1,opt,name=channel,proto3,enum=bank.ops.v1.NotificationChannel" json:"channel,omitempty"`
	OptIn         bool                   `protobuf:"varint,2,opt,name=opt_in,json=optIn,proto3" json:"opt_in,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationPrefItem) Reset() {
	*x = NotificationPrefItem{}
	mi := &file_bank_ops_v1_ops_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPrefItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPrefItem) ProtoMessage() {}

func (x *NotificationPrefItem) ProtoReflect() protoreflect.Message {
	mi := &file_bank_ops_v1_ops_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPrefItem.ProtoReflect.Descriptor instead.
func (*NotificationPrefItem) Descriptor() ([]byte, []int) {
	return file_bank_ops_v1_ops_proto_rawDescGZIP(), []int{5}
}

func (x *NotificationPrefItem) GetChannel() NotificationChannel {
	if x != nil {
		return x.Channel
	}
	return NotificationChannel_NOTIFICATION_CHANNEL_UNSPECIFIED
}

func (x *NotificationPrefItem) GetOptIn() bool {
	if x != nil {
		return x.OptIn
	}
	return false
}

func (x *NotificationPrefItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Código estable de error (sin filtrar internals).
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Mensaje breve de error.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_bank_ops_v1_ops_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_ops_v1_ops_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_bank_ops_v1_ops_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_bank_ops_v1_ops_proto protoreflect.FileDescriptor

const file_bank_ops_v1_ops_proto_rawDesc = "" +
	"\n" +
	"\x15bank/ops/v1/ops.proto\x12\vbank.ops.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xa7\x01\n" +
	"\x1cGetAuditEventsByTraceRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x121\n" +
	"\x05limit\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05limit\x129\n" +
	"\tx_subject\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\bxSubject\"T\n" +
	"\x1dGetAuditEventsByTraceResponse\x123\n" +
	"\x06events\x18\x01 \x03(\v2\x1b.bank.ops.v1.AuditEventItemR\x06events\"\x86\x01\n" +
	"\x0eAuditEventItem\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\"y\n" +
	"\x1bGetNotificationPrefsRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x129\n" +
	"\tx_subject\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\bxSubject\"W\n" +
	"\x1cGetNotificationPrefsResponse\x127\n" +
	"\x05prefs\x18\x01 \x03(\v2!.bank.ops.v1.NotificationPrefItemR\x05prefs\"\xa4\x01\n" +
	"\x14NotificationPrefItem\x12:\n" +
	"\achannel\x18\x01 \x01(\x0e2 .bank.ops.v1.NotificationChannelR\achannel\x12\x15\n" +
	"\x06opt_in\x18\x02 \x01(\bR\x05optIn\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"=\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x98\x01\n" +
	"\x13NotificationChannel\x12$\n" +
	" NOTIFICATION_CHANNEL_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aNOTIFICATION_CHANNEL_EMAIL\x10\x01\x12\x1c\n" +
	"\x18NOTIFICATION_CHANNEL_SMS\x10\x02\x12\x1d\n" +
	"\x19NOTIFICATION_CHANNEL_PUSH\x10\x032~\n" +
	"\fAuditService\x12n\n" +
	"\x15GetAuditEventsByTrace\x12).bank.ops.v1.GetAuditEventsByTraceRequest\x1a*.bank.ops.v1.GetAuditEventsByTraceResponse2\x83\x01\n" +
	"\x14NotificationsService\x12k\n" +
	"\x14GetNotificationPrefs\x12(.bank.ops.v1.GetNotificationPrefsRequest\x1a).bank.ops.v1.GetNotificationPrefsResponseB\xae\x01\n" +
	"\x0fcom.bank.ops.v1B\bOpsProtoP\x01ZCgithub.com/imaginarybank/banking-contracts/gen/go/bank/ops/v1;opsv1\xa2\x02\x03BOX\xaa\x02\vBank.Ops.V1\xca\x02\vBank\\Ops\\V1\xe2\x02\x17Bank\\Ops\\V1\\GPBMetadata\xea\x02\rBank::Ops::V1b\x06proto3"

var (
	file_bank_ops_v1_ops_proto_rawDescOnce sync.Once
	file_bank_ops_v1_ops_proto_rawDescData []byte
)

func file_bank_ops_v1_ops_proto_rawDescGZIP() []byte {
	file_bank_ops_v1_ops_proto_rawDescOnce.Do(func() {
		file_bank_ops_v1_ops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bank_ops_v1_ops_proto_rawDesc), len(file_bank_ops_v1_ops_proto_rawDesc)))
	})
	return file_bank_ops_v1_ops_proto_rawDescData
}

var file_bank_ops_v1_ops_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bank_ops_v1_ops_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_bank_ops_v1_ops_proto_goTypes = []any{
	(NotificationChannel)(0),              // 0: bank.ops.v1.NotificationChannel
	(*GetAuditEventsByTraceRequest)(nil),  // 1: bank.ops.v1.GetAuditEventsByTraceRequest
	(*GetAuditEventsByTraceResponse)(nil), // 2: bank.ops.v1.GetAuditEventsByTraceResponse
	(*AuditEventItem)(nil),                // 3: bank.ops.v1.AuditEventItem
	(*GetNotificationPrefsRequest)(nil),   // 4: bank.ops.v1.GetNotificationPrefsRequest
	(*GetNotificationPrefsResponse)(nil),  // 5: bank.ops.v1.GetNotificationPrefsResponse
	(*NotificationPrefItem)(nil),          // 6: bank.ops.v1.NotificationPrefItem
	(*ErrorResponse)(nil),                 // 7: bank.ops.v1.ErrorResponse
	(*wrapperspb.Int32Value)(nil),         // 8: google.protobuf.Int32Value
	(*wrapperspb.StringValue)(nil),        // 9: google.protobuf.StringValue
	(*timestamppb.Timestamp)(nil),         // 10: google.protobuf.Timestamp
}
var file_bank_ops_v1_ops_proto_depIdxs = []int32{
	8,  // 0: bank.ops.v1.GetAuditEventsByTraceRequest.limit:type_name -> google.protobuf.Int32Value
	9,  // 1: bank.ops.v1.GetAuditEventsByTraceRequest.x_subject:type_name -> google.protobuf.StringValue
	3,  // 2: bank.ops.v1.GetAuditEventsByTraceResponse.events:type_name -> bank.ops.v1.AuditEventItem
	10, // 3: bank.ops.v1.AuditEventItem.occurred_at:type_name -> google.protobuf.Timestamp
	9,  // 4: bank.ops.v1.GetNotificationPrefsRequest.x_subject:type_name -> google.protobuf.StringValue
	6,  // 5: bank.ops.v1.GetNotificationPrefsResponse.prefs:type_name -> bank.ops.v1.NotificationPrefItem
	0,  // 6: bank.ops.v1.NotificationPrefItem.channel:type_name -> bank.ops.v1.NotificationChannel
	10, // 7: bank.ops.v1.NotificationPrefItem.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 8: bank.ops.v1.AuditService.GetAuditEventsByTrace:input_type -> bank.ops.v1.GetAuditEventsByTraceRequest
	4,  // 9: bank.ops.v1.NotificationsService.GetNotificationPrefs:input_type -> bank.ops.v1.GetNotificationPrefsRequest
	2,  // 10: bank.ops.v1.AuditService.GetAuditEventsByTrace:output_type -> bank.ops.v1.GetAuditEventsByTraceResponse
	5,  // 11: bank.ops.v1.NotificationsService.GetNotificationPrefs:output_type -> bank.ops.v1.GetNotificationPrefsResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_bank_ops_v1_ops_proto_init() }
func file_bank_ops_v1_ops_proto_init() {
	if File_bank_ops_v1_ops_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bank_ops_v1_ops_proto_rawDesc), len(file_bank_ops_v1_ops_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_bank_ops_v1_ops_proto_goTypes,
		DependencyIndexes: file_bank_ops_v1_ops_proto_depIdxs,
		EnumInfos:         file_bank_ops_v1_ops_proto_enumTypes,
		MessageInfos:      file_bank_ops_v1_ops_proto_msgTypes,
	}.Build()
	File_bank_ops_v1_ops_proto = out.File
	file_bank_ops_v1_ops_proto_goTypes = nil
	file_bank_ops_v1_ops_proto_depIdxs = nil
}
