openapi: 3.0.3
info:
  title: Identity & Onboarding API
  version: 1.0.0
servers:
  - url: https://identity.bank.local/api/v1
paths:
  /identity/onboarding/registrations:
    post:
      operationId: startRegistration
      summary: Inicia el proceso de onboarding con datos KYC (con imágenes en base64).
      tags: [Onboarding]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationStartRequest'
      responses:
        '201':
          description: Registro de intención de onboarding creado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationStartResponse'

  /identity/oidc/login:
    post:
      operationId: startOidcLogin
      summary: Inicia login OIDC usando PKCE (y PAR si está configurado).
      tags: [OidcAuth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OidcStartLoginRequest'
      responses:
        '200':
          description: URL de autorización a la que el BFF debe redirigir al navegador.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OidcStartLoginResponse'
  /identity/oidc/token:
    post:
      operationId: completeOidcLogin
      summary: Completa el login OIDC, intercambiando code por tokens.
      tags: [OidcAuth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OidcTokenRequest'
      responses:
        '200':
          description: Datos de identidad más tokens para uso interno del BFF.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OidcTokenResponse'


components:
  schemas:
    RegistrationStartRequest:
      type: object
      description: Datos KYC iniciales para crear intención de registro.
      properties:
        channel:
          type: string
          example: web
        nationalId:
          type: string
          description: Número de cédula.
        nationalIdIssueDate:
          type: string
          format: date
          description: Fecha de expedición de la cédula.
        fingerprintCode:
          type: string
          description: Código dactilar.
        idDocumentFrontBase64:
          type: string
          description: Imagen de cédula (frontal) en base64.
        selfieBase64:
          type: string
          description: Selfie del usuario en base64.
        monthlyIncome:
          type: number
          format: double
        occupationType:
          type: string
          enum: [student, employee, self_employed, unemployed, retired]
        email:
          type: string
          format: email
        phone:
          type: string
      required:
        - channel
        - nationalId
        - nationalIdIssueDate
        - fingerprintCode
        - idDocumentFrontBase64
        - selfieBase64
        - monthlyIncome
        - occupationType
        - email
        - phone

    RegistrationStartResponse:
      type: object
      properties:
        registrationId:
          type: string
          format: uuid
        state:
          type: string
          example: started
        createdAt:
          type: string
          format: date-time
      required: [registrationId, state, createdAt]


    OidcStartLoginRequest:
      type: object
      properties:
        channel:
          type: string
          example: web
        redirectAfterLogin:
          type: string
          example: /home
      required: [channel, redirectAfterLogin]

    OidcStartLoginResponse:
      type: object
      properties:
        authorizationUrl:
          type: string
          format: uri
        state:
          type: string
      required: [authorizationUrl, state]

    OidcTokenRequest:
      type: object
      properties:
        code:
          type: string
        state:
          type: string
        ip:
          type: string
          format: ipv4
        userAgent:
          type: string
        channel:
          type: string
          example: web
      required: [code, state, ip, userAgent, channel]

    OidcTokenResponse:
      type: object
      properties:
        identityId:
          type: string
          format: uuid
        subjectIdOidc:
          type: string
        provider:
          type: string
          example: authentik
        user:
          $ref: '#/components/schemas/OidcUser'
        tokens:
          $ref: '#/components/schemas/OidcTokens'
        redirectAfterLogin:
          type: string
      required: [identityId, subjectIdOidc, provider, user, tokens, redirectAfterLogin]

    OidcUser:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        roles:
          type: array
          items:
            type: string

    OidcTokens:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        expiresIn:
          type: integer
          format: int64
      required: [accessToken, refreshToken, expiresIn]
