apiVersion: 1

datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: loki          # <— Loki para saltar Traces -> Logs
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: true
        mappedTags:
          - key: service.name
            value: service          # label en Loki (arriba lo definimos)
      serviceMap:
        datasourceUid: loki
