AWSTemplateFormatVersion: '2010-09-09'
Description: "20-data: RDS Postgres (private) + Secrets (DB_DSN per service) + KYC S3 bucket (private)"

Parameters:
  ProjectName:
    Type: String
    Default: imaginarybank
  Env:
    Type: String
    AllowedValues: [dev, prod]

  DbEngineVersion:
    Type: String
    Default: "16.3"

  DbInstanceClass:
    Type: String
    Default: "db.t4g.micro"
  DbAllocatedStorageGb:
    Type: Number
    Default: 20

  DbMultiAz:
    Type: String
    AllowedValues: ["true","false"]
    Default: "false"

  DbBackupRetentionDays:
    Type: Number
    Default: 7

  DbDeletionProtection:
    Type: String
    AllowedValues: ["true","false"]
    Default: "false"

  DbName:
    Type: String
    Default: imaginarybankdb

  DbMasterUsername:
    Type: String
    Default: masteruser
  DbMasterPassword:
    Type: String
    NoEcho: true
    MinLength: 16

  KycBucketName:
    Type: String
    Default: ""
    Description: "Si vacío, se genera uno. Recomendado: bank-kyc-<env>-<account>"

  KycCorsAllowedOrigins:
    Type: CommaDelimitedList
    Default: "http://localhost:4200"

Conditions:
  UseFixedKycBucketName: !Not [!Equals [!Ref KycBucketName, ""]]
  IsMultiAz: !Equals [!Ref DbMultiAz, "true"]
  IsDeletionProtection: !Equals [!Ref DbDeletionProtection, "true"]

Resources:
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub "${ProjectName}-${Env}-rds-subnet-group"
      SubnetIds:
        Fn::Split:
          - ","
          - Fn::ImportValue:
              Fn::Sub: "${ProjectName}-${Env}-PrivateSubnetIds"

  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "${ProjectName}-${Env}-rds-sg"
      VpcId:
        Fn::ImportValue: !Sub "${ProjectName}-${Env}-VpcId"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId:
            Fn::ImportValue: !Sub "${ProjectName}-${Env}-MicrosSecurityGroupId"

  PostgresDb:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub "${ProjectName}-${Env}-pg"
      Engine: postgres
      EngineVersion: !Ref DbEngineVersion
      DBInstanceClass: !Ref DbInstanceClass
      AllocatedStorage: !Ref DbAllocatedStorageGb
      StorageType: gp3
      StorageEncrypted: true
      PubliclyAccessible: false
      MultiAZ: !If [IsMultiAz, true, false]
      BackupRetentionPeriod: !Ref DbBackupRetentionDays
      DeletionProtection: !If [IsDeletionProtection, true, false]
      DBName: !Ref DbName
      MasterUsername: !Ref DbMasterUsername
      MasterUserPassword: !Ref DbMasterPassword
      VPCSecurityGroups:
        - !Ref DbSecurityGroup
      DBSubnetGroupName: !Ref DbSubnetGroup

  IdentityDbSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "bank/${Env}/db/identity"
      SecretString: !Sub |
        {"DB_DSN":"postgres://${DbMasterUsername}:${DbMasterPassword}@${PostgresDb.Endpoint.Address}:${PostgresDb.Endpoint.Port}/${DbName}?sslmode=require"}

  AccountDbSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "bank/${Env}/db/account"
      SecretString: !Sub |
        {"DB_DSN":"postgres://${DbMasterUsername}:${DbMasterPassword}@${PostgresDb.Endpoint.Address}:${PostgresDb.Endpoint.Port}/${DbName}?sslmode=require"}

  LedgerDbSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "bank/${Env}/db/ledger"
      SecretString: !Sub |
        {"DB_DSN":"postgres://${DbMasterUsername}:${DbMasterPassword}@${PostgresDb.Endpoint.Address}:${PostgresDb.Endpoint.Port}/${DbName}?sslmode=require"}

  KycBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [UseFixedKycBucketName, !Ref KycBucketName, !Ref "AWS::NoValue"]
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: !Ref KycCorsAllowedOrigins
            AllowedMethods: ["PUT", "GET", "HEAD"]
            AllowedHeaders: ["*"]
            ExposedHeaders: ["ETag"]
            MaxAge: 3000

  KycBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref KycBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "arn:aws:s3:::${KycBucket}"
              - !Sub "arn:aws:s3:::${KycBucket}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"

Outputs:
  DbEndpoint:
    Value: !GetAtt PostgresDb.Endpoint.Address
  DbPort:
    Value: !GetAtt PostgresDb.Endpoint.Port

  IdentityDbSecretArn:
    Value: !Ref IdentityDbSecret
  AccountDbSecretArn:
    Value: !Ref AccountDbSecret
  LedgerDbSecretArn:
    Value: !Ref LedgerDbSecret

  KycBucketNameOut:
    Value: !Ref KycBucket
  KycBucketArnOut:
    Value: !Sub "arn:aws:s3:::${KycBucket}"
