// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: accounts.proto

package accountspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCustomerAccountByIDAndTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AccountType   string                 `protobuf:"bytes,2,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerAccountByIDAndTypeRequest) Reset() {
	*x = GetCustomerAccountByIDAndTypeRequest{}
	mi := &file_accounts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerAccountByIDAndTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerAccountByIDAndTypeRequest) ProtoMessage() {}

func (x *GetCustomerAccountByIDAndTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerAccountByIDAndTypeRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerAccountByIDAndTypeRequest) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *GetCustomerAccountByIDAndTypeRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *GetCustomerAccountByIDAndTypeRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

type GetCustomerAccountByIDAndTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerAccountByIDAndTypeResponse) Reset() {
	*x = GetCustomerAccountByIDAndTypeResponse{}
	mi := &file_accounts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerAccountByIDAndTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerAccountByIDAndTypeResponse) ProtoMessage() {}

func (x *GetCustomerAccountByIDAndTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerAccountByIDAndTypeResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerAccountByIDAndTypeResponse) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *GetCustomerAccountByIDAndTypeResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type CreateCustomerAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CustomerId     int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AccountType    string                 `protobuf:"bytes,2,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	InitialDeposit float64                `protobuf:"fixed64,3,opt,name=initial_deposit,json=initialDeposit,proto3" json:"initial_deposit,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCustomerAccountRequest) Reset() {
	*x = CreateCustomerAccountRequest{}
	mi := &file_accounts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerAccountRequest) ProtoMessage() {}

func (x *CreateCustomerAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomerAccountRequest) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCustomerAccountRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreateCustomerAccountRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *CreateCustomerAccountRequest) GetInitialDeposit() float64 {
	if x != nil {
		return x.InitialDeposit
	}
	return 0
}

func (x *CreateCustomerAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateCustomerAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerAccountResponse) Reset() {
	*x = CreateCustomerAccountResponse{}
	mi := &file_accounts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerAccountResponse) ProtoMessage() {}

func (x *CreateCustomerAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateCustomerAccountResponse) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCustomerAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CustomerId    int64                  `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AccountType   string                 `protobuf:"bytes,3,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Balance       float64                `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	OpenAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=open_at,json=openAt,proto3" json:"open_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_accounts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{4}
}

func (x *Account) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Account) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *Account) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *Account) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Account) GetOpenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenAt
	}
	return nil
}

var File_accounts_proto protoreflect.FileDescriptor

const file_accounts_proto_rawDesc = "" +
	"\n" +
	"\x0eaccounts.proto\x12\vaccounts.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"j\n" +
	"$GetCustomerAccountByIDAndTypeRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\x12!\n" +
	"\faccount_type\x18\x02 \x01(\tR\vaccountType\"W\n" +
	"%GetCustomerAccountByIDAndTypeResponse\x12.\n" +
	"\aaccount\x18\x01 \x01(\v2\x14.accounts.v1.AccountR\aaccount\"\xa7\x01\n" +
	"\x1cCreateCustomerAccountRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\x12!\n" +
	"\faccount_type\x18\x02 \x01(\tR\vaccountType\x12'\n" +
	"\x0finitial_deposit\x18\x03 \x01(\x01R\x0einitialDeposit\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"O\n" +
	"\x1dCreateCustomerAccountResponse\x12.\n" +
	"\aaccount\x18\x01 \x01(\v2\x14.accounts.v1.AccountR\aaccount\"\xef\x01\n" +
	"\aAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\x03R\n" +
	"customerId\x12!\n" +
	"\faccount_type\x18\x03 \x01(\tR\vaccountType\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x01R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x123\n" +
	"\aopen_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06openAt2\x8a\x02\n" +
	"\x0fAccountsService\x12n\n" +
	"\x15CreateCustomerAccount\x12).accounts.v1.CreateCustomerAccountRequest\x1a*.accounts.v1.CreateCustomerAccountResponse\x12\x86\x01\n" +
	"\x1dGetCustomerAccountByIDAndType\x121.accounts.v1.GetCustomerAccountByIDAndTypeRequest\x1a2.accounts.v1.GetCustomerAccountByIDAndTypeResponseBEZCgithub.com/tagoKoder/accounts/proto/genproto/go/accounts;accountspbb\x06proto3"

var (
	file_accounts_proto_rawDescOnce sync.Once
	file_accounts_proto_rawDescData []byte
)

func file_accounts_proto_rawDescGZIP() []byte {
	file_accounts_proto_rawDescOnce.Do(func() {
		file_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounts_proto_rawDesc), len(file_accounts_proto_rawDesc)))
	})
	return file_accounts_proto_rawDescData
}

var file_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_accounts_proto_goTypes = []any{
	(*GetCustomerAccountByIDAndTypeRequest)(nil),  // 0: accounts.v1.GetCustomerAccountByIDAndTypeRequest
	(*GetCustomerAccountByIDAndTypeResponse)(nil), // 1: accounts.v1.GetCustomerAccountByIDAndTypeResponse
	(*CreateCustomerAccountRequest)(nil),          // 2: accounts.v1.CreateCustomerAccountRequest
	(*CreateCustomerAccountResponse)(nil),         // 3: accounts.v1.CreateCustomerAccountResponse
	(*Account)(nil),                               // 4: accounts.v1.Account
	(*timestamppb.Timestamp)(nil),                 // 5: google.protobuf.Timestamp
}
var file_accounts_proto_depIdxs = []int32{
	4, // 0: accounts.v1.GetCustomerAccountByIDAndTypeResponse.account:type_name -> accounts.v1.Account
	4, // 1: accounts.v1.CreateCustomerAccountResponse.account:type_name -> accounts.v1.Account
	5, // 2: accounts.v1.Account.open_at:type_name -> google.protobuf.Timestamp
	2, // 3: accounts.v1.AccountsService.CreateCustomerAccount:input_type -> accounts.v1.CreateCustomerAccountRequest
	0, // 4: accounts.v1.AccountsService.GetCustomerAccountByIDAndType:input_type -> accounts.v1.GetCustomerAccountByIDAndTypeRequest
	3, // 5: accounts.v1.AccountsService.CreateCustomerAccount:output_type -> accounts.v1.CreateCustomerAccountResponse
	1, // 6: accounts.v1.AccountsService.GetCustomerAccountByIDAndType:output_type -> accounts.v1.GetCustomerAccountByIDAndTypeResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_accounts_proto_init() }
func file_accounts_proto_init() {
	if File_accounts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounts_proto_rawDesc), len(file_accounts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accounts_proto_goTypes,
		DependencyIndexes: file_accounts_proto_depIdxs,
		MessageInfos:      file_accounts_proto_msgTypes,
	}.Build()
	File_accounts_proto = out.File
	file_accounts_proto_goTypes = nil
	file_accounts_proto_depIdxs = nil
}
