// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: accounts.proto

package accountspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountsService_CreateCustomerAccount_FullMethodName         = "/accounts.v1.AccountsService/CreateCustomerAccount"
	AccountsService_GetCustomerAccountByIDAndType_FullMethodName = "/accounts.v1.AccountsService/GetCustomerAccountByIDAndType"
)

// AccountsServiceClient is the client API for AccountsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountsServiceClient interface {
	CreateCustomerAccount(ctx context.Context, in *CreateCustomerAccountRequest, opts ...grpc.CallOption) (*CreateCustomerAccountResponse, error)
	GetCustomerAccountByIDAndType(ctx context.Context, in *GetCustomerAccountByIDAndTypeRequest, opts ...grpc.CallOption) (*GetCustomerAccountByIDAndTypeResponse, error)
}

type accountsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountsServiceClient(cc grpc.ClientConnInterface) AccountsServiceClient {
	return &accountsServiceClient{cc}
}

func (c *accountsServiceClient) CreateCustomerAccount(ctx context.Context, in *CreateCustomerAccountRequest, opts ...grpc.CallOption) (*CreateCustomerAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCustomerAccountResponse)
	err := c.cc.Invoke(ctx, AccountsService_CreateCustomerAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsServiceClient) GetCustomerAccountByIDAndType(ctx context.Context, in *GetCustomerAccountByIDAndTypeRequest, opts ...grpc.CallOption) (*GetCustomerAccountByIDAndTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomerAccountByIDAndTypeResponse)
	err := c.cc.Invoke(ctx, AccountsService_GetCustomerAccountByIDAndType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsServiceServer is the server API for AccountsService service.
// All implementations must embed UnimplementedAccountsServiceServer
// for forward compatibility.
type AccountsServiceServer interface {
	CreateCustomerAccount(context.Context, *CreateCustomerAccountRequest) (*CreateCustomerAccountResponse, error)
	GetCustomerAccountByIDAndType(context.Context, *GetCustomerAccountByIDAndTypeRequest) (*GetCustomerAccountByIDAndTypeResponse, error)
	mustEmbedUnimplementedAccountsServiceServer()
}

// UnimplementedAccountsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountsServiceServer struct{}

func (UnimplementedAccountsServiceServer) CreateCustomerAccount(context.Context, *CreateCustomerAccountRequest) (*CreateCustomerAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomerAccount not implemented")
}
func (UnimplementedAccountsServiceServer) GetCustomerAccountByIDAndType(context.Context, *GetCustomerAccountByIDAndTypeRequest) (*GetCustomerAccountByIDAndTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerAccountByIDAndType not implemented")
}
func (UnimplementedAccountsServiceServer) mustEmbedUnimplementedAccountsServiceServer() {}
func (UnimplementedAccountsServiceServer) testEmbeddedByValue()                         {}

// UnsafeAccountsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountsServiceServer will
// result in compilation errors.
type UnsafeAccountsServiceServer interface {
	mustEmbedUnimplementedAccountsServiceServer()
}

func RegisterAccountsServiceServer(s grpc.ServiceRegistrar, srv AccountsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAccountsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountsService_ServiceDesc, srv)
}

func _AccountsService_CreateCustomerAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).CreateCustomerAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_CreateCustomerAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).CreateCustomerAccount(ctx, req.(*CreateCustomerAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsService_GetCustomerAccountByIDAndType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerAccountByIDAndTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServiceServer).GetCustomerAccountByIDAndType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsService_GetCustomerAccountByIDAndType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServiceServer).GetCustomerAccountByIDAndType(ctx, req.(*GetCustomerAccountByIDAndTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountsService_ServiceDesc is the grpc.ServiceDesc for AccountsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accounts.v1.AccountsService",
	HandlerType: (*AccountsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomerAccount",
			Handler:    _AccountsService_CreateCustomerAccount_Handler,
		},
		{
			MethodName: "GetCustomerAccountByIDAndType",
			Handler:    _AccountsService_GetCustomerAccountByIDAndType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts.proto",
}
