AWSTemplateFormatVersion: "2010-09-09"
Description: "30-identity-cognito: User Pool + App Client (Auth Code + PKCE) + MFA TOTP"

Parameters:
  AppName:
    Type: String
    Default: "imabank"

  Env:
    Type: String
    Default: "dev"
    AllowedValues: ["dev", "prod"]

  RegionShort:
    Type: String
    Default: "use1"

  CognitoDomainPrefix:
    Type: String
    Description: "Unique domain prefix for Cognito hosted UI in this region (must be unique)."

  PublicAppUrl:
    Type: String
    Description: "Base URL of the public app (dev: http://localhost:4200, prod: https://FQDN)."

  CallbackPaths:
    Type: CommaDelimitedList
    Default: "/bff/login/callback"

  LogoutPaths:
    Type: CommaDelimitedList
    Default: "/login"

  MfaMode:
    Type: String
    Default: "OPTIONAL"
    AllowedValues: ["OFF", "OPTIONAL", "ON"]
    Description: "Cognito user pool MFA mode. Recommended: OPTIONAL for dev/tesis; enforce step-up via policy/app."

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      UserPoolName: !Sub "${AppName}-${Env}-${RegionShort}-userpool"

      # Onboarding manda: solo admin puede crear usuarios
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true

      UsernameAttributes:
        - email

      AutoVerifiedAttributes:
        - email

      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: true
          TemporaryPasswordValidityDays: 3

      # MFA (TOTP)
      MfaConfiguration: !Ref MfaMode
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
      SoftwareTokenMfaConfiguration:
        Enabled: true

      # Atributo mínimo útil para vínculo con tu banca (no guardes KYC aquí)
      Schema:
        - Name: customer_id
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Required: false
          StringAttributeConstraints:
            MinLength: "1"
            MaxLength: "64"

      UserPoolAddOns:
        AdvancedSecurityMode: AUDIT

      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE

      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT

      Tags:
        app: !Ref AppName
        env: !Ref Env
        managed_by: cloudformation
        compliance: asvs-l3

  UserPoolClientWeb:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub "${AppName}-${Env}-${RegionShort}-web-bff"

      # PKCE: cliente público (sin secret)
      GenerateSecret: false

      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - profile

      SupportedIdentityProviders:
        - COGNITO

      # Construimos URLs absolutas: PublicAppUrl + paths
      CallbackURLs: !Split
        - ","
        - !Join
          - ","
          - - !Sub "${PublicAppUrl}${CallbackPaths}"

      LogoutURLs: !Split
        - ","
        - !Join
          - ","
          - - !Sub "${PublicAppUrl}${LogoutPaths}"

      ExplicitAuthFlows:
        # Permitimos SRP/password y refresh token (BFF canjea tokens)
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

      PreventUserExistenceErrors: ENABLED

      AccessTokenValidity: 10
      IdTokenValidity: 10
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref CognitoDomainPrefix
      UserPoolId: !Ref UserPool

Outputs:
  UserPoolId:
    Value: !Ref UserPool
    Export:
      Name: !Sub "${AppName}-${Env}-${RegionShort}-cognito-userpool-id"

  UserPoolArn:
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub "${AppName}-${Env}-${RegionShort}-cognito-userpool-arn"

  UserPoolClientId:
    Value: !Ref UserPoolClientWeb
    Export:
      Name: !Sub "${AppName}-${Env}-${RegionShort}-cognito-client-id"

  CognitoDomain:
    Value: !Sub "https://${CognitoDomainPrefix}.auth.${AWS::Region}.amazoncognito.com"
    Export:
      Name: !Sub "${AppName}-${Env}-${RegionShort}-cognito-domain"

  IssuerUrl:
    Value: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}"
    Export:
      Name: !Sub "${AppName}-${Env}-${RegionShort}-cognito-issuer"
