/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { CreateBeneficiaryRequestDto } from '../model/createBeneficiaryRequest';
// @ts-ignore
import { CreateBeneficiaryResponseDto } from '../model/createBeneficiaryResponse';
// @ts-ignore
import { CreatePaymentRequestDto } from '../model/createPaymentRequest';
// @ts-ignore
import { CreatePaymentResponseDto } from '../model/createPaymentResponse';
// @ts-ignore
import { ErrorResponseDto } from '../model/errorResponse';
// @ts-ignore
import { GetPaymentResponseDto } from '../model/getPaymentResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';


export interface CreateBeneficiaryRequestParams {
    xCSRFToken: string;
    idempotencyKey: string;
    createBeneficiaryRequestDto: CreateBeneficiaryRequestDto;
}

export interface ExecutePaymentRequestParams {
    idempotencyKey: string;
    xCSRFToken: string;
    createPaymentRequestDto: CreatePaymentRequestDto;
}

export interface GetPaymentStatusRequestParams {
    id: string;
}


@Injectable({
  providedIn: 'root'
})
export class PaymentsApi extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Crea beneficiario (MVP)
     * @endpoint post /api/v1/beneficiaries
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public createBeneficiary(requestParameters: CreateBeneficiaryRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<CreateBeneficiaryResponseDto>;
    public createBeneficiary(requestParameters: CreateBeneficiaryRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<CreateBeneficiaryResponseDto>>;
    public createBeneficiary(requestParameters: CreateBeneficiaryRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<CreateBeneficiaryResponseDto>>;
    public createBeneficiary(requestParameters: CreateBeneficiaryRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const xCSRFToken = requestParameters?.xCSRFToken;
        if (xCSRFToken === null || xCSRFToken === undefined) {
            throw new Error('Required parameter xCSRFToken was null or undefined when calling createBeneficiary.');
        }
        const idempotencyKey = requestParameters?.idempotencyKey;
        if (idempotencyKey === null || idempotencyKey === undefined) {
            throw new Error('Required parameter idempotencyKey was null or undefined when calling createBeneficiary.');
        }
        const createBeneficiaryRequestDto = requestParameters?.createBeneficiaryRequestDto;
        if (createBeneficiaryRequestDto === null || createBeneficiaryRequestDto === undefined) {
            throw new Error('Required parameter createBeneficiaryRequestDto was null or undefined when calling createBeneficiary.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xCSRFToken !== undefined && xCSRFToken !== null) {
            localVarHeaders = localVarHeaders.set('X-CSRF-Token', String(xCSRFToken));
        }
        if (idempotencyKey !== undefined && idempotencyKey !== null) {
            localVarHeaders = localVarHeaders.set('Idempotency-Key', String(idempotencyKey));
        }

        // authentication (cookieAuth) required

        // authentication (csrfAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('csrfAuth', 'X-CSRF-Token', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/beneficiaries`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<CreateBeneficiaryResponseDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: createBeneficiaryRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Ejecuta un pago
     * Orquestación: - BFF valida request (formato, currency, amount). - (Condicional) RefreshSession para access_token downstream. - Payments.PostPayment con Idempotency-Key. Interno (Payments): - Valida cuentas y límites (Accounts Internal). - Reserva hold (Accounts Internal). - Postea journal/outbox. 
     * @endpoint post /api/v1/payments
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public executePayment(requestParameters: ExecutePaymentRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<CreatePaymentResponseDto>;
    public executePayment(requestParameters: ExecutePaymentRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<CreatePaymentResponseDto>>;
    public executePayment(requestParameters: ExecutePaymentRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<CreatePaymentResponseDto>>;
    public executePayment(requestParameters: ExecutePaymentRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const idempotencyKey = requestParameters?.idempotencyKey;
        if (idempotencyKey === null || idempotencyKey === undefined) {
            throw new Error('Required parameter idempotencyKey was null or undefined when calling executePayment.');
        }
        const xCSRFToken = requestParameters?.xCSRFToken;
        if (xCSRFToken === null || xCSRFToken === undefined) {
            throw new Error('Required parameter xCSRFToken was null or undefined when calling executePayment.');
        }
        const createPaymentRequestDto = requestParameters?.createPaymentRequestDto;
        if (createPaymentRequestDto === null || createPaymentRequestDto === undefined) {
            throw new Error('Required parameter createPaymentRequestDto was null or undefined when calling executePayment.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (idempotencyKey !== undefined && idempotencyKey !== null) {
            localVarHeaders = localVarHeaders.set('Idempotency-Key', String(idempotencyKey));
        }
        if (xCSRFToken !== undefined && xCSRFToken !== null) {
            localVarHeaders = localVarHeaders.set('X-CSRF-Token', String(xCSRFToken));
        }

        // authentication (cookieAuth) required

        // authentication (csrfAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('csrfAuth', 'X-CSRF-Token', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/payments`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<CreatePaymentResponseDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: createPaymentRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtiene estado/detalle de un pago
     * @endpoint get /api/v1/payments/{id}
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public getPaymentStatus(requestParameters: GetPaymentStatusRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GetPaymentResponseDto>;
    public getPaymentStatus(requestParameters: GetPaymentStatusRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GetPaymentResponseDto>>;
    public getPaymentStatus(requestParameters: GetPaymentStatusRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GetPaymentResponseDto>>;
    public getPaymentStatus(requestParameters: GetPaymentStatusRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const id = requestParameters?.id;
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getPaymentStatus.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (cookieAuth) required

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/payments/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GetPaymentResponseDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
