/**
 * BFF Web API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { BeginWebauthnAssertionResponseDto } from '../model/beginWebauthnAssertionResponse';
// @ts-ignore
import { BeginWebauthnRegistrationRequestDto } from '../model/beginWebauthnRegistrationRequest';
// @ts-ignore
import { BeginWebauthnRegistrationResponseDto } from '../model/beginWebauthnRegistrationResponse';
// @ts-ignore
import { ErrorResponseDto } from '../model/errorResponse';
// @ts-ignore
import { FinishWebauthnAssertionRequestDto } from '../model/finishWebauthnAssertionRequest';
// @ts-ignore
import { FinishWebauthnRegistrationRequestDto } from '../model/finishWebauthnRegistrationRequest';
// @ts-ignore
import { WebauthnSuccessResponseDto } from '../model/webauthnSuccessResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';


export interface BeginWebauthnAssertionRequestParams {
    xCSRFToken: string;
}

export interface BeginWebauthnRegistrationRequestParams {
    xCSRFToken: string;
    beginWebauthnRegistrationRequestDto?: BeginWebauthnRegistrationRequestDto;
}

export interface FinishWebauthnAssertionRequestParams {
    xCSRFToken: string;
    finishWebauthnAssertionRequestDto: FinishWebauthnAssertionRequestDto;
}

export interface FinishWebauthnRegistrationRequestParams {
    xCSRFToken: string;
    finishWebauthnRegistrationRequestDto: FinishWebauthnRegistrationRequestDto;
}


@Injectable({
  providedIn: 'root'
})
export class WebauthnApi extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Inicia assertion WebAuthn (MFA)
     * @endpoint post /bff/webauthn/assertion/begin
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public beginWebauthnAssertion(requestParameters: BeginWebauthnAssertionRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<BeginWebauthnAssertionResponseDto>;
    public beginWebauthnAssertion(requestParameters: BeginWebauthnAssertionRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<BeginWebauthnAssertionResponseDto>>;
    public beginWebauthnAssertion(requestParameters: BeginWebauthnAssertionRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<BeginWebauthnAssertionResponseDto>>;
    public beginWebauthnAssertion(requestParameters: BeginWebauthnAssertionRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const xCSRFToken = requestParameters?.xCSRFToken;
        if (xCSRFToken === null || xCSRFToken === undefined) {
            throw new Error('Required parameter xCSRFToken was null or undefined when calling beginWebauthnAssertion.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xCSRFToken !== undefined && xCSRFToken !== null) {
            localVarHeaders = localVarHeaders.set('X-CSRF-Token', String(xCSRFToken));
        }

        // authentication (cookieAuth) required

        // authentication (csrfAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('csrfAuth', 'X-CSRF-Token', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/bff/webauthn/assertion/begin`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<BeginWebauthnAssertionResponseDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Inicia registro WebAuthn (passkey)
     * @endpoint post /bff/webauthn/registration/begin
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public beginWebauthnRegistration(requestParameters: BeginWebauthnRegistrationRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<BeginWebauthnRegistrationResponseDto>;
    public beginWebauthnRegistration(requestParameters: BeginWebauthnRegistrationRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<BeginWebauthnRegistrationResponseDto>>;
    public beginWebauthnRegistration(requestParameters: BeginWebauthnRegistrationRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<BeginWebauthnRegistrationResponseDto>>;
    public beginWebauthnRegistration(requestParameters: BeginWebauthnRegistrationRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const xCSRFToken = requestParameters?.xCSRFToken;
        if (xCSRFToken === null || xCSRFToken === undefined) {
            throw new Error('Required parameter xCSRFToken was null or undefined when calling beginWebauthnRegistration.');
        }
        const beginWebauthnRegistrationRequestDto = requestParameters?.beginWebauthnRegistrationRequestDto;

        let localVarHeaders = this.defaultHeaders;
        if (xCSRFToken !== undefined && xCSRFToken !== null) {
            localVarHeaders = localVarHeaders.set('X-CSRF-Token', String(xCSRFToken));
        }

        // authentication (cookieAuth) required

        // authentication (csrfAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('csrfAuth', 'X-CSRF-Token', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/bff/webauthn/registration/begin`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<BeginWebauthnRegistrationResponseDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: beginWebauthnRegistrationRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Finaliza assertion WebAuthn (MFA)
     * @endpoint post /bff/webauthn/assertion/finish
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public finishWebauthnAssertion(requestParameters: FinishWebauthnAssertionRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<WebauthnSuccessResponseDto>;
    public finishWebauthnAssertion(requestParameters: FinishWebauthnAssertionRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<WebauthnSuccessResponseDto>>;
    public finishWebauthnAssertion(requestParameters: FinishWebauthnAssertionRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<WebauthnSuccessResponseDto>>;
    public finishWebauthnAssertion(requestParameters: FinishWebauthnAssertionRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const xCSRFToken = requestParameters?.xCSRFToken;
        if (xCSRFToken === null || xCSRFToken === undefined) {
            throw new Error('Required parameter xCSRFToken was null or undefined when calling finishWebauthnAssertion.');
        }
        const finishWebauthnAssertionRequestDto = requestParameters?.finishWebauthnAssertionRequestDto;
        if (finishWebauthnAssertionRequestDto === null || finishWebauthnAssertionRequestDto === undefined) {
            throw new Error('Required parameter finishWebauthnAssertionRequestDto was null or undefined when calling finishWebauthnAssertion.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xCSRFToken !== undefined && xCSRFToken !== null) {
            localVarHeaders = localVarHeaders.set('X-CSRF-Token', String(xCSRFToken));
        }

        // authentication (cookieAuth) required

        // authentication (csrfAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('csrfAuth', 'X-CSRF-Token', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/bff/webauthn/assertion/finish`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<WebauthnSuccessResponseDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: finishWebauthnAssertionRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Finaliza registro WebAuthn
     * @endpoint post /bff/webauthn/registration/finish
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public finishWebauthnRegistration(requestParameters: FinishWebauthnRegistrationRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<WebauthnSuccessResponseDto>;
    public finishWebauthnRegistration(requestParameters: FinishWebauthnRegistrationRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<WebauthnSuccessResponseDto>>;
    public finishWebauthnRegistration(requestParameters: FinishWebauthnRegistrationRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<WebauthnSuccessResponseDto>>;
    public finishWebauthnRegistration(requestParameters: FinishWebauthnRegistrationRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const xCSRFToken = requestParameters?.xCSRFToken;
        if (xCSRFToken === null || xCSRFToken === undefined) {
            throw new Error('Required parameter xCSRFToken was null or undefined when calling finishWebauthnRegistration.');
        }
        const finishWebauthnRegistrationRequestDto = requestParameters?.finishWebauthnRegistrationRequestDto;
        if (finishWebauthnRegistrationRequestDto === null || finishWebauthnRegistrationRequestDto === undefined) {
            throw new Error('Required parameter finishWebauthnRegistrationRequestDto was null or undefined when calling finishWebauthnRegistration.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xCSRFToken !== undefined && xCSRFToken !== null) {
            localVarHeaders = localVarHeaders.set('X-CSRF-Token', String(xCSRFToken));
        }

        // authentication (cookieAuth) required

        // authentication (csrfAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('csrfAuth', 'X-CSRF-Token', localVarHeaders);

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/bff/webauthn/registration/finish`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<WebauthnSuccessResponseDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: finishWebauthnRegistrationRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
