server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  # Logs de tu micro (escribiremos a ./logs/*.log)
  - job_name: user-service
    static_configs:
      - targets: [localhost]
        labels:
          job: user-service
          service: user-service
          __path__: /var/log/hostapp/*.log
    pipeline_stages:
      - json:
          expressions:
            time: time
            level: level
            msg: msg
            trace_id: trace_id
            span_id: span_id
            user_id: user_id
            agency_id: agency_id
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          level:
          service:
          user_id:
          agency_id:
#      - output:
#          source: msg

  # (opcional) logs de contenedores docker si montas /var/lib/docker/containers
  # - job_name: docker
  #   static_configs:
  #     - targets: [localhost]
  #       labels:
  #         job: docker
  #         __path__: /var/lib/docker/containers/*/*-json.log
  #   pipeline_stages:
  #     - docker: {}
  #     - json:
  #         expressions:
  #           trace_id: trace_id
  #           span_id: span_id
  #     - labels:
  #         container:
  #         trace_id:
  #     - output:
  #         source: log
