AWSTemplateFormatVersion: '2010-09-09'
Description: >
  00-foundation - Base compliance/support: mandatory tags, KMS keys (s3, secrets, optional logs),
  base S3 buckets (logs, optional artifacts), and a deployer IAM role.

Parameters:
  Env:
    Type: String
    AllowedValues: [dev, prod]
    Description: Environment name.

  ProjectName:
    Type: String
    Default: imaginarybank
    AllowedPattern: '^[a-z0-9-]{3,30}$'
    Description: Short project name used in resource naming (lowercase).

  Owner:
    Type: String
    Default: platform
    MaxLength: 64

  CostCenter:
    Type: String
    Default: thesis
    MaxLength: 64

  DataClassification:
    Type: String
    Default: internal
    AllowedValues: [public, internal, confidential, restricted]

  EnableKeyRotation:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'true'

  EnableLogsKmsKey:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'false'
    Description: If true, creates a dedicated KMS key for logs.

  CreateArtifactsBucket:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'false'
    Description: If true, creates an artifacts bucket.

  LogsBucketRetentionDays:
    Type: Number
    Default: 365
    MinValue: 30
    MaxValue: 3650

  ArtifactsBucketRetentionDays:
    Type: Number
    Default: 180
    MinValue: 30
    MaxValue: 3650

  DeployerRoleName:
    Type: String
    Default: ''
    Description: >
      Optional explicit name for the deployer role. If empty, a default name is used.

  DeployerPrincipalArn:
    Type: String
    Default: ''
    Description: >
      Optional principal ARN allowed to assume the deployer role. If empty, trusts account root.
  
  CreateEcrRepositories:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'true'
    Description: If true, creates ECR repositories for bff/identity/account/ledger.

  EcrScanOnPush:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'true'

  EcrTagMutability:
    Type: String
    AllowedValues: [IMMUTABLE, MUTABLE]
    Default: IMMUTABLE

  EcrLifecycleMaxImages:
    Type: Number
    Default: 50
    MinValue: 10
    MaxValue: 500

  EcrRepoBff:
    Type: String
    Default: ''
    Description: ECR repository name for BFF (e.g. imaginarybank-dev-bff)

  EcrRepoIdentity:
    Type: String
    Default: ''
    Description: ECR repository name for Identity (e.g. imaginarybank-dev-identity)

  EcrRepoAccount:
    Type: String
    Default: ''
    Description: ECR repository name for Account (e.g. imaginarybank-dev-account)

  EcrRepoLedger:
    Type: String
    Default: ''
    Description: ECR repository name for Ledger (e.g. imaginarybank-dev-ledger)


Conditions:
  UseLogsKey: !Equals [!Ref EnableLogsKmsKey, 'true']
  CreateArtifacts: !Equals [!Ref CreateArtifactsBucket, 'true']
  HasDeployerRoleName: !Not [!Equals [!Ref DeployerRoleName, '']]
  HasDeployerPrincipalArn: !Not [!Equals [!Ref DeployerPrincipalArn, '']]
  CreateEcr: !Equals [!Ref CreateEcrRepositories, 'true']


Resources:
  KmsKeyS3:
    Type: AWS::KMS::Key
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: !Sub "${ProjectName}-${Env}-kms-s3"
      EnableKeyRotation: !Ref EnableKeyRotation
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowAccountRootFullAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Sid: AllowCloudTrailUseKey
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
              - kms:CreateGrant
            Resource: "*"
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId

      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: env
          Value: !Ref Env
        - Key: owner
          Value: !Ref Owner
        - Key: cost_center
          Value: !Ref CostCenter
        - Key: data_classification
          Value: !Ref DataClassification

  KmsAliasS3:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${ProjectName}-${Env}-kms-s3"
      TargetKeyId: !Ref KmsKeyS3

  KmsKeySecrets:
    Type: AWS::KMS::Key
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: !Sub "${ProjectName}-${Env}-kms-secrets"
      EnableKeyRotation: !Ref EnableKeyRotation
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowAccountRootFullAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: env
          Value: !Ref Env
        - Key: owner
          Value: !Ref Owner
        - Key: cost_center
          Value: !Ref CostCenter
        - Key: data_classification
          Value: !Ref DataClassification

  KmsAliasSecrets:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${ProjectName}-${Env}-kms-secrets"
      TargetKeyId: !Ref KmsKeySecrets

  KmsKeyLogs:
    Condition: UseLogsKey
    Type: AWS::KMS::Key
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: !Sub "${ProjectName}-${Env}-kms-logs"
      EnableKeyRotation: !Ref EnableKeyRotation
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowAccountRootFullAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Sid: AllowCloudTrailUseKey
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
              - kms:CreateGrant
            Resource: "*"
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId

      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: env
          Value: !Ref Env
        - Key: owner
          Value: !Ref Owner
        - Key: cost_center
          Value: !Ref CostCenter
        - Key: data_classification
          Value: !Ref DataClassification

  KmsAliasLogs:
    Condition: UseLogsKey
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${ProjectName}-${Env}-kms-logs"
      TargetKeyId: !Ref KmsKeyLogs

  LogsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${ProjectName}-logs-${Env}-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !If
                - UseLogsKey
                - !GetAtt KmsKeyLogs.Arn
                - !GetAtt KmsKeyS3.Arn
      LifecycleConfiguration:
        Rules:
          - Id: expire-logs
            Status: Enabled
            ExpirationInDays: !Ref LogsBucketRetentionDays
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: env
          Value: !Ref Env
        - Key: owner
          Value: !Ref Owner
        - Key: cost_center
          Value: !Ref CostCenter
        - Key: data_classification
          Value: !Ref DataClassification

  LogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${LogsBucket}"
              - !Sub "arn:${AWS::Partition}:s3:::${LogsBucket}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"
          - Sid: AllowCloudTrailGetBucketAcl
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub "arn:${AWS::Partition}:s3:::${LogsBucket}"

          - Sid: AllowCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "arn:${AWS::Partition}:s3:::${LogsBucket}/cloudtrail/AWSLogs/${AWS::AccountId}/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
                s3:x-amz-server-side-encryption: aws:kms

          - Sid: DenyUnencryptedObjectUploads
            Effect: Deny
            Principal: "*"
            Action: "s3:PutObject"
            Resource: !Sub "arn:${AWS::Partition}:s3:::${LogsBucket}/*"
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: "aws:kms"

  ArtifactsBucket:
    Condition: CreateArtifacts
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${ProjectName}-artifacts-${Env}-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt KmsKeyS3.Arn
      LifecycleConfiguration:
        Rules:
          - Id: expire-artifacts
            Status: Enabled
            ExpirationInDays: !Ref ArtifactsBucketRetentionDays
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: env
          Value: !Ref Env
        - Key: owner
          Value: !Ref Owner
        - Key: cost_center
          Value: !Ref CostCenter
        - Key: data_classification
          Value: !Ref DataClassification

  ArtifactsBucketPolicy:
    Condition: CreateArtifacts
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${ArtifactsBucket}"
              - !Sub "arn:${AWS::Partition}:s3:::${ArtifactsBucket}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"

          - Sid: DenyUnencryptedObjectUploads
            Effect: Deny
            Principal: "*"
            Action: "s3:PutObject"
            Resource: !Sub "arn:${AWS::Partition}:s3:::${ArtifactsBucket}/*"
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: "aws:kms"

  CfnDeployerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !If
        - HasDeployerRoleName
        - !Ref DeployerRoleName
        - !Sub "${ProjectName}-${Env}-cfn-deployer"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowAssumeFromPrincipal
            Effect: Allow
            Action: "sts:AssumeRole"
            Principal:
              AWS: !If
                - HasDeployerPrincipalArn
                - !Ref DeployerPrincipalArn
                - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
      ManagedPolicyArns:
        # Demo/thesis friendly: simplify operations. Tighten later if needed.
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess"
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: env
          Value: !Ref Env
        - Key: owner
          Value: !Ref Owner
        - Key: cost_center
          Value: !Ref CostCenter
        - Key: data_classification
          Value: !Ref DataClassification

  EcrRepoBffResource:
    Condition: CreateEcr
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref EcrRepoBff
      ImageScanningConfiguration:
        ScanOnPush: !Ref EcrScanOnPush
      ImageTagMutability: !Ref EcrTagMutability
      EncryptionConfiguration:
        EncryptionType: AES256
      LifecyclePolicy:
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last ${EcrLifecycleMaxImages} images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": ${EcrLifecycleMaxImages}
                },
                "action": { "type": "expire" }
              }
            ]
          }
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: env
          Value: !Ref Env
        - Key: owner
          Value: !Ref Owner
        - Key: cost_center
          Value: !Ref CostCenter
        - Key: data_classification
          Value: !Ref DataClassification

  EcrRepoIdentityResource:
    Condition: CreateEcr
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref EcrRepoIdentity
      ImageScanningConfiguration:
        ScanOnPush: !Ref EcrScanOnPush
      ImageTagMutability: !Ref EcrTagMutability
      EncryptionConfiguration:
        EncryptionType: AES256
      LifecyclePolicy:
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last ${EcrLifecycleMaxImages} images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": ${EcrLifecycleMaxImages}
                },
                "action": { "type": "expire" }
              }
            ]
          }
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: env
          Value: !Ref Env
        - Key: owner
          Value: !Ref Owner
        - Key: cost_center
          Value: !Ref CostCenter
        - Key: data_classification
          Value: !Ref DataClassification

  EcrRepoAccountResource:
    Condition: CreateEcr
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref EcrRepoAccount
      ImageScanningConfiguration:
        ScanOnPush: !Ref EcrScanOnPush
      ImageTagMutability: !Ref EcrTagMutability
      EncryptionConfiguration:
        EncryptionType: AES256
      LifecyclePolicy:
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last ${EcrLifecycleMaxImages} images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": ${EcrLifecycleMaxImages}
                },
                "action": { "type": "expire" }
              }
            ]
          }
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: env
          Value: !Ref Env
        - Key: owner
          Value: !Ref Owner
        - Key: cost_center
          Value: !Ref CostCenter
        - Key: data_classification
          Value: !Ref DataClassification

  EcrRepoLedgerResource:
    Condition: CreateEcr
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref EcrRepoLedger
      ImageScanningConfiguration:
        ScanOnPush: !Ref EcrScanOnPush
      ImageTagMutability: !Ref EcrTagMutability
      EncryptionConfiguration:
        EncryptionType: AES256
      LifecyclePolicy:
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last ${EcrLifecycleMaxImages} images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": ${EcrLifecycleMaxImages}
                },
                "action": { "type": "expire" }
              }
            ]
          }
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: env
          Value: !Ref Env
        - Key: owner
          Value: !Ref Owner
        - Key: cost_center
          Value: !Ref CostCenter
        - Key: data_classification
          Value: !Ref DataClassification


Outputs:
  LogsBucketName:
    Value: !Ref LogsBucket
    Export:
      Name: !Sub "${ProjectName}-${Env}-LogsBucketName"

  ArtifactsBucketName:
    Condition: CreateArtifacts
    Value: !Ref ArtifactsBucket
    Export:
      Name: !Sub "${ProjectName}-${Env}-ArtifactsBucketName"

  KmsKeyS3Arn:
    Value: !GetAtt KmsKeyS3.Arn
    Export:
      Name: !Sub "${ProjectName}-${Env}-KmsKeyS3Arn"

  KmsKeySecretsArn:
    Value: !GetAtt KmsKeySecrets.Arn
    Export:
      Name: !Sub "${ProjectName}-${Env}-KmsKeySecretsArn"

  KmsKeyLogsArn:
    Condition: UseLogsKey
    Value: !GetAtt KmsKeyLogs.Arn
    Export:
      Name: !Sub "${ProjectName}-${Env}-KmsKeyLogsArn"

  CfnDeployerRoleArn:
    Value: !GetAtt CfnDeployerRole.Arn
    Export:
      Name: !Sub "${ProjectName}-${Env}-CfnDeployerRoleArn"

  EcrRepoBffUri:
    Condition: CreateEcr
    Value: !GetAtt EcrRepoBffResource.RepositoryUri
    Export:
      Name: !Sub "${ProjectName}-${Env}-EcrRepoBffUri"

  EcrRepoIdentityUri:
    Condition: CreateEcr
    Value: !GetAtt EcrRepoIdentityResource.RepositoryUri
    Export:
      Name: !Sub "${ProjectName}-${Env}-EcrRepoIdentityUri"

  EcrRepoAccountUri:
    Condition: CreateEcr
    Value: !GetAtt EcrRepoAccountResource.RepositoryUri
    Export:
      Name: !Sub "${ProjectName}-${Env}-EcrRepoAccountUri"

  EcrRepoLedgerUri:
    Condition: CreateEcr
    Value: !GetAtt EcrRepoLedgerResource.RepositoryUri
    Export:
      Name: !Sub "${ProjectName}-${Env}-EcrRepoLedgerUri"
